// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my profile",
  description: "Return the signed-in BacPath user's profile: name, stream, points, level, streak, and role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const uid = ctx.getUserId();
    const client = sb(ctx);
    const [{ data: profile, error: pErr }, { data: role }] = await Promise.all([
      client.from("profiles").select("full_name, points, level, streak, stream, teacher_subject").eq("id", uid).maybeSingle(),
      client.from("user_roles").select("role").eq("user_id", uid).maybeSingle()
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    const result = { ...profile, role: role?.role ?? "student", email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool2({
  name: "list_tasks",
  title: "List my study tasks",
  description: "List the signed-in user's BacPath study tasks. Optionally filter by done status.",
  inputSchema: {
    done: z.boolean().optional().describe("If set, only return tasks with this done status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ done }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb2(ctx).from("tasks").select("id, title, subject, duration, points, done, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: true });
    if (typeof done === "boolean") q = q.eq("done", done);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool3({
  name: "create_task",
  title: "Create study task",
  description: "Add a new BacPath study task to the signed-in user's plan.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Task title."),
    subject: z2.enum(["math", "physics", "chemistry", "history"]).describe("Subject key."),
    duration: z2.number().int().min(1).max(600).describe("Estimated duration in minutes."),
    points: z2.number().int().min(1).max(1e4).describe("Points awarded on completion.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, subject, duration, points }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("tasks").insert({ user_id: ctx.getUserId(), title, subject, duration, points, done: false }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Task created: ${data.id}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/complete-task.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var complete_task_default = defineTool4({
  name: "complete_task",
  title: "Mark task done",
  description: "Mark one of the signed-in user's tasks as completed and award its points.",
  inputSchema: {
    task_id: z3.string().uuid().describe("Task id to mark done.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ task_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb4(ctx);
    const { data: task, error: tErr } = await client.from("tasks").select("id, points, done, user_id").eq("id", task_id).maybeSingle();
    if (tErr) return { content: [{ type: "text", text: tErr.message }], isError: true };
    if (!task) return { content: [{ type: "text", text: "Task not found" }], isError: true };
    if (task.done) return { content: [{ type: "text", text: "Task already completed" }], structuredContent: { task } };
    const { error: uErr } = await client.from("tasks").update({ done: true }).eq("id", task_id);
    if (uErr) return { content: [{ type: "text", text: uErr.message }], isError: true };
    const { data: profile } = await client.from("profiles").select("points").eq("id", ctx.getUserId()).maybeSingle();
    const newPoints = (profile?.points ?? 0) + (task.points ?? 0);
    const newLevel = Math.floor(newPoints / 1e3) + 1;
    await client.from("profiles").update({ points: newPoints, level: newLevel }).eq("id", ctx.getUserId());
    return {
      content: [{ type: "text", text: `Task completed. Awarded ${task.points} points. Total: ${newPoints} (level ${newLevel}).` }],
      structuredContent: { task_id, awarded: task.points, points: newPoints, level: newLevel }
    };
  }
});

// src/lib/mcp/tools/list-questions.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_questions_default = defineTool5({
  name: "list_questions",
  title: "List Q&A questions",
  description: "List questions posted to the BacPath Q&A board, newest first.",
  inputSchema: {
    subject: z4.string().trim().optional().describe("Filter by subject text."),
    answered: z4.boolean().optional().describe("If set, filter by whether the question has been answered."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subject, answered, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb5(ctx).from("qa_questions").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (subject) q = q.ilike("subject", subject);
    if (typeof answered === "boolean") {
      q = answered ? q.not("answer", "is", null) : q.is("answer", null);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { questions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/ask-question.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var ask_question_default = defineTool6({
  name: "ask_question",
  title: "Ask a Q&A question",
  description: "Post a new question to the BacPath Q&A board on behalf of the signed-in user.",
  inputSchema: {
    subject: z5.string().trim().min(1).describe("Subject (e.g. \u0631\u064A\u0627\u0636\u064A\u0627\u062A\u060C \u0641\u064A\u0632\u064A\u0627\u0621)."),
    question: z5.string().trim().min(3).describe("The question text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ subject, question }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb6(ctx);
    const { data: profile } = await client.from("profiles").select("full_name").eq("id", ctx.getUserId()).maybeSingle();
    const { data, error } = await client.from("qa_questions").insert({
      user_id: ctx.getUserId(),
      user_name: profile?.full_name || ctx.getUserEmail() || "\u0637\u0627\u0644\u0628",
      subject,
      question
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Question posted: ${data.id}` }],
      structuredContent: { question: data }
    };
  }
});

// src/lib/mcp/tools/list-live-sessions.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^4.4.3";
function sb7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_live_sessions_default = defineTool7({
  name: "list_live_sessions",
  title: "List live sessions",
  description: "List BacPath live sessions (upcoming by default). Only registered students can see the stream link.",
  inputSchema: {
    when: z6.enum(["upcoming", "past", "all"]).optional().describe("Filter: upcoming (default), past, or all."),
    limit: z6.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ when, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const filter = when ?? "upcoming";
    let q = sb7(ctx).from("live_sessions").select("*").limit(limit ?? 20);
    const now = (/* @__PURE__ */ new Date()).toISOString();
    if (filter === "upcoming") q = q.gte("scheduled_at", now).order("scheduled_at", { ascending: true });
    else if (filter === "past") q = q.lt("scheduled_at", now).order("scheduled_at", { ascending: false });
    else q = q.order("scheduled_at", { ascending: false });
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hqobknpxyxtcxhyrijrn";
var mcp_default = defineMcp({
  name: "bacpath-mcp",
  title: "BacPath MCP",
  version: "0.1.0",
  instructions: "Tools for BacPath, an Algerian baccalaureate study platform. Use these tools to read the signed-in student's profile, manage their study tasks, browse live sessions, and read or post questions to the Q&A board. All tools act as the authenticated user; database access is protected by RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    list_tasks_default,
    create_task_default,
    complete_task_default,
    list_live_sessions_default,
    list_questions_default,
    ask_question_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
